### ISSUE TITLE
expand_world_size.cfg not syncing for not admin players

### ISSUE THREAD

**Issue by xzahalko** [JereKuusela/valheim-expand_world_size#1]
Hi Jare Kuusela,

we have spent a lot of time with testing and found that expand_world_size.cfg is not synced for not admin players.

We have World radius = 15000
Error occured on logout for not admin players:
[Info   :Expand World Size] Regenerating the world.
[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
ExpandWorldSize.WaterLayerFix.Refresh (EnvMan obj) (at <392b5d168a064a2d92eaa219227f5211>:0)
ExpandWorldSize.WorldInfo.Generate () (at <392b5d168a064a2d92eaa219227f5211>:0)
ExpandWorldSize.EWS.Regenerate () (at <392b5d168a064a2d92eaa219227f5211>:0)

Admins got clean log without error.
Looks like after normal player logout, got an error, log in the game, corrupt dedicated server world file.

We solved it by adding modified expand_world_size.cfg to players profile directly.

Thanks a lot for your help

**Comment by xzahalko** [comment]
Still thinking about it, maybe I should write "not writing a expand_world_size.cfg in local config folder" instead of syncing.

**Comment by xzahalko** [comment]
now after another testing, looks like corrupted db problem is not connected to the error from expand_world_sice,
but just Vaheilm

**Comment by JereKuusela** [comment]
Yes, config sync only updates in-memory. The files are not touched on clients.

**Comment by xzahalko** [comment]
Ok, thanks for an explanation.
