### ISSUE TITLE
No Deep North with world stretch.

### ISSUE THREAD

**Issue by piotrkowalczyk95** [JereKuusela/valheim-expand_world_size#2]
Hello. I've been testing mod for few days now, trying to see how different multipliers affect generated world and I've noticed that with stretching every biome seems to be on the map excluding Deep North. Whenever I set stretch value to 2 and more the biome would just disappear from the map. No idea if it's me doing something wrong or if it's fixable issue.

**Comment by JereKuusela** [comment]
Fixed on latest v1.12.
