### ISSUE TITLE
Minimap size greater than 1 causes FPS stuttering and drop

### ISSUE THREAD

**Issue by jneb802** [JereKuusela/valheim-expand_world_size#7]
With world radius size = 20k and minimap size = 1, there is no stuttering. With world radius size = 20k and minimap size = 2, there is frequent stuttering and FPS drop. 

Steps to reproduce:

1. Create a new world with radius = 20k and minimap = 1. 
2. Enter world
3. Walk character forward for 30 seconds, observer FPS
4. Change configuration setting, minimap size. Change from 1 to 2. Save
5. Let world regenerate. Upon success, proceed.
6. Move character forward for 30 seconds, observe FPS stuttering and drop.

See here for video of above steps: https://youtu.be/8kyDKi0reXk

**Comment by toddlersizedsharkcage** [comment]
Same happens with an existing world booted up with 2 set for the minimap size as well with this repeating constantly in the console (no other errors):

[Error  : Unity Log] ArgumentException: Texture2D.SetPixels: size of data to be filled was larger than the size of data available in the source array. (Texture '_Minimap m_forestMaskTexture')
Stack trace:
UnityEngine.Texture2D.SetPixels (System.Int32 x, System.Int32 y, System.Int32 blockWidth, System.Int32 blockHeight, UnityEngine.Color[] colors, System.Int32 miplevel) (at <ab14d35a27c043688812ae199c64b5aa>:0)
UnityEngine.Texture2D.SetPixels (UnityEngine.Color[] colors) (at <ab14d35a27c043688812ae199c64b5aa>:0)
Minimap.TryLoadMinimapTextureData () (at <da52c09f594f4a7480000b7420815ba7>:0)
Minimap.Update () (at <da52c09f594f4a7480000b7420815ba7>:0)
