### ISSUE TITLE
Increasing world size only adds ocean beyond vanilla limits.

### ISSUE THREAD

**Issue by RolePlayerVintage** [JereKuusela/valheim-expand_world_size#9]

**Comment by RolePlayerVintage** [comment]
![image](https://github.com/JereKuusela/valheim-expand_world_size/assets/107450581/b75af846-4505-4c7c-b9f2-3f2b45159f57)

**Comment by Bedroom25** [comment]
Running into a similar thing. except my world is mostly covered in Ashlands sea. 
![image](https://github.com/JereKuusela/valheim-expand_world_size/assets/170019774/ecbfac02-c91d-42b3-ba05-b4554f265f4c)
